```{r}
library(tidyverse)
library(lubridate)
```

```{r, read_data, cache=TRUE}

set.seed(203741092)
truck_type1 <- read_csv("truck_type-1.csv") %>%
    rename(type1 = type)
truck_type2 <- read_csv("truck_type-2.csv") %>%
    rename(type2 = type)
truck_type3 <- read_csv("truck_type-3.csv") %>%
    rename(type3 = type)
truck_type4 <- read_csv("truck_type-4.csv") %>%
    rename(type4 = type)
truck_type5 <- read_csv("truck_type-5.csv") %>%
    rename(type5 = type)
factor1 <- read_csv("factor-1.csv") %>%
    rename(factor_type1 = factor_type)
factor2 <- read_csv("factor-2.csv") %>%
    rename(factor_type2 = factor_type)
factor3 <- read_csv("factor-3.csv") %>%
    rename(factor_type3 = factor_type)
factor4 <- read_csv("factor-4.csv") %>%
    rename(factor_type4 = factor_type)
factor5 <- read_csv("factor-5.csv") %>%
    rename(factor_type5 = factor_type)

accident <- read_csv("Motor_Vehicle_Collisions_-_Crashes.csv") %>%
    left_join(truck_type1, by = "COLLISION_ID") %>%
    left_join(truck_type2, by = "COLLISION_ID") %>%
    left_join(truck_type3, by = "COLLISION_ID") %>%
    left_join(truck_type4, by = "COLLISION_ID") %>%
    left_join(truck_type5, by = "COLLISION_ID") %>%
    left_join(factor1, by = "COLLISION_ID") %>%
    left_join(factor2, by = "COLLISION_ID") %>%
    left_join(factor3, by = "COLLISION_ID") %>%
    left_join(factor4, by = "COLLISION_ID") %>%
    left_join(factor5, by = "COLLISION_ID") %>%
    mutate(
        `VEHICLE TYPE CODE 1` = type1,
        `VEHICLE TYPE CODE 2` = type2,
        `VEHICLE TYPE CODE 3` = type3,
        `VEHICLE TYPE CODE 4` = type4,
        `VEHICLE TYPE CODE 5` = type5,
        `CONTRIBUTING FACTOR VEHICLE 1` = factor_type1,
        `CONTRIBUTING FACTOR VEHICLE 2` = factor_type2,
        `CONTRIBUTING FACTOR VEHICLE 3` = factor_type3,
        `CONTRIBUTING FACTOR VEHICLE 4` = factor_type4,
        `CONTRIBUTING FACTOR VEHICLE 5` = factor_type5
    )

weather12_14 <- read_csv("noaa12_14.csv")
weather15_17 <- read_csv("noaa15_17.csv")
weather18_21 <- read_csv("noaa18_21.csv")
weather12_21 <- weather12_14 %>%
    add_row(weather15_17) %>%
    add_row(weather18_21)


weather <- weather12_21 %>%
    select(-c(STATION, NAME, ELEVATION)) %>%
    arrange(DATE) %>%
    group_by(DATE) %>%
    summarise(across(AWND:WT22, ~ mean(as.numeric(.x), na.rm = TRUE))) %>%
    replace(is.na(.), 0) %>%
    rename(
        Foggy = WT01,
        Heavy.Fog = WT02,
        Ice.Fog = WT22,
        Ground.Fog = WT21,
        Mist = WT13,
        Thunder = WT03,
        Small.Hail = WT04,
        Hail = WT05,
        Rime = WT06,
        Smoke = WT08,
        Blowing.Snow = WT09,
        Snow = WT18,
        Tornado = WT10,
        Damaging.Wind = WT11,
        Drizzle = WT14,
        Freezing.Drizzle = WT15,
        Rain = WT16,
        Unknown.Precipitation = WT19
    )
```

```{r na analysis}
t.test(
    (accident %>% filter(!is.na(`BOROUGH`)))$`NUMBER OF PERSONS INJURED`,
    (accident %>% filter(is.na(`BOROUGH`)))$`NUMBER OF PERSONS INJURED`
)
```

```{r, data_cleaning, cache=TRUE}
accident <- accident %>%
    mutate(
        `CRASH DATE` = mdy(`CRASH DATE`)
    )

accident %>%
    summarize(
        `CRASH DATE min` = min(`CRASH DATE`),
        `CRASH DATE max` = max(`CRASH DATE`)
    )

accident %>%
    mutate(
        `CRASH MONTH` = month(`CRASH DATE`),
        `CRASH YEAR` = year(`CRASH DATE`)
    )
```


```{r Time Separation}

accident <- accident %>%
    mutate(
        time_range = case_when(
            hour(`CRASH TIME`) < 4 ~ "Late Night",
            hour(`CRASH TIME`) < 8 ~ "Morning",
            hour(`CRASH TIME`) < 12 ~ "Midday",
            hour(`CRASH TIME`) < 16 ~ "Afternoon",
            hour(`CRASH TIME`) < 20 ~ "Evening",
            hour(`CRASH TIME`) < 24 ~ "Late Night"
        )
    )
```


```{r Sunset, echo=FALSE, cache=TRUE}
sunset <- read_csv("sunset1.csv")
for (i in 2:12) {
    sunset <- sunset %>% add_row(read_csv(paste0("sunset", i, ".csv")))
}

sunset <- sunset %>%
    mutate(
        Day = paste("2020", str_replace(Day, "^.*,", "")),
        Date = ymd(Day),
        month = month(Date),
        day = day(Date)
    )

accidents <- accident %>%
    mutate(
        month = month(`CRASH DATE`),
        day = day(`CRASH DATE`)
    ) %>%
    full_join(sunset, by = c("month", "day")) %>%
    mutate(
        hour = hour(`CRASH TIME`),
        minute = minute(`CRASH TIME`),
        Sunrise = hms(Sunrise),
        Sunset = hms(Sunset)
    ) %>%
    mutate(
        sunrise_hour = hour(Sunrise),
        sunrise_minute = minutes(Sunrise),
        sunset_hour = hour(Sunset),
        sunset_minute = minute(Sunset)
    ) %>%
    mutate(
        DayLight = ifelse(
            (hour >= sunrise_hour & hour < sunset_hour) |
                (hour == sunrise_hour & minute >= sunrise_minute) |
                (hour == sunset_hour & minute <= sunset_minute),
            1,
            0
        )
    )
```


```{r Location Separation}

accidents <- accidents %>%
    mutate(
        LOCATION_SPLIT = case_when(
            LATITUDE > 40.778374 ~ case_when(
                LONGITUDE < -73.937672 ~ "0",
                LONGITUDE < -73.860884 ~ "1",
                T ~ "2",
            ),
            LATITUDE > 40.712806 ~ case_when(
                LONGITUDE < -73.976068 ~ "3",
                LONGITUDE < -73.827198 ~ "4",
                T ~ "5",
            ),
            T ~ case_when(
                LONGITUDE < -73.976068 ~ "6",
                LONGITUDE < -73.827198 ~ "7",
                T ~ "8",
            )
        )
    )
```


```{r weather join}
accidents_full <- accidents %>%
    rename(DATE = `CRASH DATE`) %>%
    mutate(DATE = ymd(DATE)) %>%
    rename("CROSS STREET" = "CROSS STREET NAME") %>%
    full_join(weather, by = "DATE")

accidents_full <- accidents_full %>%
    mutate(
        SNOW = ifelse(is.na(SNOW), 0, SNOW),
        PRCP = ifelse(is.na(PRCP), 0, PRCP),
        TMAX = ifelse(is.na(TMAX), 0, TMAX),
        TMIN = ifelse(is.na(TMIN), 0, TMIN),
        Foggy = ifelse(is.na(Foggy), 0, Foggy)
    )
```

```{r visualization}
accidents_full %>%
    summarise(
        `NoFog` = sum(ifelse((Foggy + Heavy.Fog + Smoke), 0, 1), na.rm = T) / n(),
        Fog = sum(Foggy, na.rm = T) / n(),
        HeavyFog = sum(Heavy.Fog, na.rm = T) / n(),
        Smoke = sum(Smoke, na.rm = T) / n(),
        IceFog = sum(Ice.Fog, na.rm = T) / n(),
    ) %>%
    pivot_longer(
        everything(),
        names_to = "Fog Type",
        values_to = "Proportion"
    ) %>%
    ggplot() +
    geom_col(aes(x = `Fog Type`, y = Proportion), fill = "steelblue") +
    theme_bw() +
    ggtitle("Proportion of Accidents by Fog Type")

accidents_full %>%
    filter(`NUMBER OF PERSONS INJURED` > 0) %>%
    summarise(
        `NoFog` = sum(ifelse(Foggy + Heavy.Fog + Smoke, 0, 1), na.rm = T) / n(),
        `Fog` = sum(Foggy, na.rm = T) / n(),
        `HeavyFog` = sum(Heavy.Fog, na.rm = T) / n(),
        `Smoke` = sum(Smoke, na.rm = T) / n(),
        `IceFog` = sum(Ice.Fog, na.rm = T) / n(),
    ) %>%
    pivot_longer(
        everything(),
        names_to = "Fog Type",
        values_to = "Proportion"
    ) %>%
    ggplot() +
    geom_col(
        aes(x = `Fog Type`, y = Proportion),
        fill = "steelblue", width = 0.5
    ) +
    theme_bw() +
    ggtitle("Proportion of Injury Accidents by Fog Type")


accidents_full %>%
    summarise(
        NoFog = mean(`NUMBER OF PERSONS INJURED` *
            (ifelse(Foggy + Heavy.Fog + Smoke, 0, 1)), na.rm = T),
        Fog = mean(`NUMBER OF PERSONS INJURED` * Foggy, na.rm = T),
        HeavyFog = mean(`NUMBER OF PERSONS INJURED` * Heavy.Fog, na.rm = T),
        Smoke = mean(`NUMBER OF PERSONS INJURED` * Smoke, na.rm = T),
        IceFog = mean(`NUMBER OF PERSONS INJURED` * Ice.Fog, na.rm = T)
    ) %>%
    pivot_longer(
        everything(),
        names_to = "Fog Type",
        values_to = "mean_injury"
    ) %>%
    ggplot(aes(`Fog Type`, mean_injury)) +
    geom_col(fill = "steelblue", width = 0.5) +
    xlab("Fog Type") +
    ylab("Mean Injury (Base on degree of fog)") +
    theme_bw() +
    ggtitle("Mean Injury by Fog Type")

accidents_full %>%
    filter(`NUMBER OF PERSONS INJURED` > 5) %>%
    group_by(DayLight) %>%
    summarise(
        DayLight = as.factor(DayLight),
        injury = `NUMBER OF PERSONS INJURED`
    ) %>%
    drop_na() %>%
    ggplot(aes(DayLight, injury)) +
    ylab("Injury") +
    geom_boxplot() +
    ggtitle("Box Plot of Injury by Daylight (Injury Number > 5)")


accidents_full %>%
    mutate(
        prcp_range = case_when(
            PRCP == 0 | is.na(PRCP) ~ "No Rain",
            PRCP < 0.4 ~ "Light Rain",
            PRCP < 1.0 ~ "Moderate Rain",
            PRCP < 2.0 ~ "Heavy Rain",
            PRCP < 4.0 ~ "Very Heavy Rain",
            PRCP < 10.0 ~ "Extreme Rain",
            T ~ "Super Extreme Rain"
        )
    ) %>%
    group_by(prcp_range) %>%
    summarise(injury = mean(`NUMBER OF PERSONS INJURED`, na.rm = T)) %>%
    ggplot(
        aes(x = `prcp_range`, y = injury)
    ) +
    xlab("Precipitation Level") +
    ylab("Injury") +
    geom_col(fill = "steelblue")


(accidents_full) %>%
    mutate(
        snow_range = case_when(
            SNOW == 0 | is.na(SNOW) ~ "No Snow",
            SNOW < 0.4 * 13 ~ "Light Snow",
            SNOW < 1.0 * 13 ~ "Moderate Snow",
            SNOW < 2.0 * 13 ~ "Heavy Snow",
            SNOW < 4.0 * 13 ~ "Very Heavy Snow",
            SNOW < 10.0 * 13 ~ "Extreme Snow",
            T ~ "Super Extreme Snow"
        )
    ) %>%
    group_by(snow_range) %>%
    summarise(injury = mean(`NUMBER OF PERSONS INJURED`, na.rm = T)) %>%
    ggplot(
        aes(x = `snow_range`, y = injury)
    ) +
    xlab("Snow Level") +
    ylab("Injury") +
    geom_col(fill = "steelblue")

(accidents_full[sample(nrow(accidents_full), 5000), ]) %>%
    ggplot(aes(PRCP, `NUMBER OF PERSONS INJURED`)) +
    geom_point()

```

```{r}
accidents_full <- accidents_full %>%
    mutate(
        truck_involved = (
            (`VEHICLE TYPE CODE 1` == "Truck") |
                (`VEHICLE TYPE CODE 2` == "Truck") |
                (`VEHICLE TYPE CODE 3` == "Truck") |
                (`VEHICLE TYPE CODE 4` == "Truck") |
                (`VEHICLE TYPE CODE 5` == "Truck")
        ),
        two_wheel_involved = (
            (`VEHICLE TYPE CODE 1` %in% c("Bike", "Motor")) |
                (`VEHICLE TYPE CODE 2` %in% c("Bike", "Motor")) |
                (`VEHICLE TYPE CODE 3` %in% c("Bike", "Motor")) |
                (`VEHICLE TYPE CODE 4` %in% c("Bike", "Motor")) |
                (`VEHICLE TYPE CODE 5` %in% c("Bike", "Motor"))
        ),
        unconcious_driver = (
            (factor_type1 %in% c("Drug", "Fatigue")) |
                 (factor_type2 %in% c("Drug", "Fatigue")) |
                 (factor_type3 %in% c("Drug", "Fatigue")) |
                 (factor_type4 %in% c("Drug", "Fatigue")) |
                 (factor_type5 %in% c("Drug", "Fatigue"))
        ),
        crazy_driver = (
            factor_type1 == "Crazy Driver" |
                factor_type2 == "Crazy Driver" |
                factor_type3 == "Crazy Driver" |
                factor_type4 == "Crazy Driver" |
                factor_type5 == "Crazy Driver" )
        )%>%
    mutate(
        at_crossing = !is.na(`CROSS STREET`)
    )
```


```{r model}
# seperate trainning data and testing data
af <- accidents_full %>%
    select(
        `NUMBER OF PERSONS INJURED`,
        `LONGITUDE`,
        `LATITUDE`,
        Foggy,
        Smoke,
        Heavy.Fog,
        PRCP,
        SNOW,
        Ice.Fog,
        DayLight,
        `BOROUGH`,
        `LOCATION_SPLIT`,
        at_crossing,
        two_wheel_involved,
        truck_involved,
        unconcious_driver,
        crazy_driver
    ) %>%
    drop_na()
set.seed(123)

rows <- sample(nrow(af)) # Randomly reorder the row of the dataset.
train_num <- as.integer(length(rows) * 0.8) # Separating the dataset to two parts, one for training the model, and the other for testing the model.
test_num <- train_num + 1
len <- nrow(af %>% drop_na())

train_df <- af[rows, ][1:train_num, ]
test_df <- af[rows, ][test_num:len, ]

```


```{r sample & train}
samples <- sample(nrow(train_df), 150000)

train_df[samples, ] %>%
    filter(`LONGITUDE` != 0 & `LATITUDE` != 0) %>%
    filter(`NUMBER OF PERSONS INJURED` > 0) %>%
    ggplot() +
    geom_point(
        aes(
            x = `LATITUDE`, y = `LONGITUDE`,
            color =
                (
                    LATITUDE > 40.64 & LATITUDE < 40.68 &
                        LONGITUDE > -73.965 & LONGITUDE < -73.89
                ) | (
                    LATITUDE > 40.68 & LATITUDE < 40.77 &
                        LONGITUDE > -74.02 & LONGITUDE < -73.955
                ) | (
                    LATITUDE > 40.79 & LATITUDE < 40.825 &
                        LONGITUDE > -74.059 & LONGITUDE < -73.885
                ) | (
                    LATITUDE > 40.695 & LATITUDE < 40.72 &
                        LONGITUDE > -73.96 & LONGITUDE < -73.935
                ) | (
                    LATITUDE > 40.847 & LATITUDE < 40.865 &
                        LONGITUDE > -73.91 & LONGITUDE < -73.89
                )
        ),
        alpha = 0.006
    ) +
    labs(color = "Serious Area")
```

```{r serious accident location}

selector <- function(LATITUDE, LONGITUDE) {
    (
        LATITUDE > 40.64 & LATITUDE < 40.68 &
            LONGITUDE > -73.965 & LONGITUDE < -73.89
    ) | (
        LATITUDE > 40.68 & LATITUDE < 40.77 &
            LONGITUDE > -74.02 & LONGITUDE < -73.955
    ) | (
        LATITUDE > 40.79 & LATITUDE < 40.825 &
            LONGITUDE > -74.059 & LONGITUDE < -73.885
    ) | (
        LATITUDE > 40.695 & LATITUDE < 40.72 &
            LONGITUDE > -73.96 & LONGITUDE < -73.935
    ) | (
        LATITUDE > 40.847 & LATITUDE < 40.865 &
            LONGITUDE > -73.91 & LONGITUDE < -73.89
    )
}

train_df <- train_df %>%
    mutate(
        serious_area = selector(`LATITUDE`, `LONGITUDE`)
    )
    
test_df = test_df %>% 
    mutate(
        serious_area = selector(`LATITUDE`, `LONGITUDE`)
    )
```

```{r Accuracy (Step)}

test.accuracy <- function(model, test_df) {
    prediction.full <- model %>% predict(test_df, type = "response");
    predicted.full <- ifelse(prediction.full > 0.5, TRUE, FALSE);
    observed.full <- (test_df$`NUMBER OF PERSONS INJURED` > 0);
    return(mean(predicted.full == observed.full));
}

full.model <- glm(
    (`NUMBER OF PERSONS INJURED` > 0) ~ Foggy + Smoke + Heavy.Fog + Ice.Fog + PRCP + SNOW + Ice.Fog + DayLight + at_crossing + two_wheel_involved + truck_involved + serious_area + unconcious_driver + crazy_driver,
    data = (train_df),
    family = "binomial"
)

summary(full.model)

test.accuracy(full.model, test_df)

```


```{r Model Selection}

# Foggy + Smoke + Heavy.Fog + Ice.Fog + PRCP + SNOW + Ice.Fog + DayLight + at_crossing + two_wheel_involved + truck_involved + serious_area + unconcious_driver + crazy_driver

step1a.model <- glm(
    (`NUMBER OF PERSONS INJURED` > 0) ~ Foggy,
    data = (train_df),
    family = "binomial"
)

step1b.model <- glm(
    (`NUMBER OF PERSONS INJURED` > 0) ~ Smoke,
    data = (train_df),
    family = "binomial"
)

step1c.model <- glm(
    (`NUMBER OF PERSONS INJURED` > 0) ~ Heavy.Fog,
    data = (train_df),
    family = "binomial"
)

step1d.model <- glm(
    (`NUMBER OF PERSONS INJURED` > 0) ~ Ice.Fog,
    data = (train_df),
    family = "binomial"
)


step1e.model <- glm(
    (`NUMBER OF PERSONS INJURED` > 0) ~ PRCP,
    data = (train_df),
    family = "binomial"
)

step1f.model <- glm(
    (`NUMBER OF PERSONS INJURED` > 0) ~ SNOW,
    data = (train_df),
    family = "binomial"
)

step1g.model <- glm(
    (`NUMBER OF PERSONS INJURED` > 0) ~ DayLight,
    data = (train_df),
    family = "binomial"
)

step1h.model <- glm(
    (`NUMBER OF PERSONS INJURED` > 0) ~ at_crossing,
    data = (train_df),
    family = "binomial"
)

step1i.model <- glm(
    (`NUMBER OF PERSONS INJURED` > 0) ~ two_wheel_involved,
    data = (train_df),
    family = "binomial"
)

step1j.model <- glm(
    (`NUMBER OF PERSONS INJURED` > 0) ~ truck_involved,
    data = (train_df),
    family = "binomial"
)

step1k.model <- glm(
    (`NUMBER OF PERSONS INJURED` > 0) ~ serious_area,
    data = (train_df),
    family = "binomial"
)

step1l.model <- glm(
    (`NUMBER OF PERSONS INJURED` > 0) ~ unconcious_driver,
    data = (train_df),
    family = "binomial"
)

step1m.model <- glm(
    (`NUMBER OF PERSONS INJURED` > 0) ~ crazy_driver,
    data = (train_df),
    family = "binomial"
)

# Foggy + Smoke + Heavy.Fog  + Ice.Fog + PRCP + SNOW + DayLight + at_crossing + two_wheel_involved + truck_involved + serious_area + unconcious_driver + crazy_driver

round1 <- tibble(
     model = c(
        "Foggy",
        "Smoke",
        "Heavy.Fog",
        "Ice.Fog",
        "PRCP",
        "SNOW",
        "DayLight",
        "at_crossing",
        "two_wheel_involved",
        "truck_involved",
        "serious_area",
        "unconcious_driver",
        "crazy_driver"
    ),
    aic_round1 = c(
        step1a.model$aic,
        step1b.model$aic,
        step1c.model$aic,
        step1d.model$aic,
        step1e.model$aic,
        step1f.model$aic,
        step1g.model$aic,
        step1h.model$aic,
        step1i.model$aic,
        step1j.model$aic,
        step1k.model$aic,
        step1l.model$aic,
        step1m.model$aic
    )
)

round1 %>%
    arrange(aic_round1)

```

```{r}
# two wheel

step2a.model <- glm(
    (`NUMBER OF PERSONS INJURED` > 0) ~ two_wheel_involved + Foggy,
    data = (train_df),
    family = "binomial"
)

step2b.model <- glm(
    (`NUMBER OF PERSONS INJURED` > 0) ~ two_wheel_involved + Smoke,
    data = (train_df),
    family = "binomial"
)

step2c.model <- glm(
    (`NUMBER OF PERSONS INJURED` > 0) ~ two_wheel_involved + Heavy.Fog,
    data = (train_df),
    family = "binomial"
)

step2d.model <- glm(
    (`NUMBER OF PERSONS INJURED` > 0) ~ two_wheel_involved + Ice.Fog,
    data = (train_df),
    family = "binomial"
)


step2e.model <- glm(
    (`NUMBER OF PERSONS INJURED` > 0) ~ two_wheel_involved + PRCP,
    data = (train_df),
    family = "binomial"
)

step2f.model <- glm(
    (`NUMBER OF PERSONS INJURED` > 0) ~ two_wheel_involved + SNOW,
    data = (train_df),
    family = "binomial"
)

step2g.model <- glm(
    (`NUMBER OF PERSONS INJURED` > 0) ~ two_wheel_involved + DayLight,
    data = (train_df),
    family = "binomial"
)

step2h.model <- glm(
    (`NUMBER OF PERSONS INJURED` > 0) ~ two_wheel_involved + at_crossing,
    data = (train_df),
    family = "binomial"
)

# i

step2j.model <- glm(
    (`NUMBER OF PERSONS INJURED` > 0) ~ two_wheel_involved + truck_involved,
    data = (train_df),
    family = "binomial"
)

step2k.model <- glm(
    (`NUMBER OF PERSONS INJURED` > 0) ~ two_wheel_involved + serious_area,
    data = (train_df),
    family = "binomial"
)

step2l.model <- glm(
    (`NUMBER OF PERSONS INJURED` > 0) ~ two_wheel_involved + unconcious_driver,
    data = (train_df),
    family = "binomial"
)

step2m.model <- glm(
    (`NUMBER OF PERSONS INJURED` > 0) ~ two_wheel_involved + crazy_driver,
    data = (train_df),
    family = "binomial"
)

# Foggy + Smoke + Heavy.Fog  + Ice.Fog + PRCP + SNOW + DayLight + at_crossing + two_wheel_involved + truck_involved + serious_area + unconcious_driver + crazy_driver

round2 <- round1 %>%
    mutate (
        aic_round2 = c(
        step2a.model$aic,
        step2b.model$aic,
        step2c.model$aic,
        step2d.model$aic,
        step2e.model$aic,
        step2f.model$aic,
        step2g.model$aic,
        step2h.model$aic,
        0,
        step2j.model$aic,
        step2k.model$aic,
        step2l.model$aic,
        step2m.model$aic
    ))

round2 %>%
    arrange(aic_round2)

```
```{r}
# truck invovled

step3a.model <- glm(
    (`NUMBER OF PERSONS INJURED` > 0) ~ two_wheel_involved + truck_involved + Foggy,
    data = (train_df),
    family = "binomial"
)

step3b.model <- glm(
    (`NUMBER OF PERSONS INJURED` > 0) ~ two_wheel_involved + truck_involved +Smoke,
    data = (train_df),
    family = "binomial"
)

step3c.model <- glm(
    (`NUMBER OF PERSONS INJURED` > 0) ~ two_wheel_involved + truck_involved +Heavy.Fog,
    data = (train_df),
    family = "binomial"
)

step3d.model <- glm(
    (`NUMBER OF PERSONS INJURED` > 0) ~ two_wheel_involved + truck_involved +Ice.Fog,
    data = (train_df),
    family = "binomial"
)


step3e.model <- glm(
    (`NUMBER OF PERSONS INJURED` > 0) ~ two_wheel_involved + truck_involved +PRCP,
    data = (train_df),
    family = "binomial"
)

step3f.model <- glm(
    (`NUMBER OF PERSONS INJURED` > 0) ~ two_wheel_involved + truck_involved +SNOW,
    data = (train_df),
    family = "binomial"
)

step3g.model <- glm(
    (`NUMBER OF PERSONS INJURED` > 0) ~ two_wheel_involved + truck_involved +DayLight,
    data = (train_df),
    family = "binomial"
)

step3h.model <- glm(
    (`NUMBER OF PERSONS INJURED` > 0) ~ two_wheel_involved + truck_involved +at_crossing,
    data = (train_df),
    family = "binomial"
)

# i

# j

step3k.model <- glm(
    (`NUMBER OF PERSONS INJURED` > 0) ~ two_wheel_involved + truck_involved + serious_area,
    data = (train_df),
    family = "binomial"
)

step3l.model <- glm(
    (`NUMBER OF PERSONS INJURED` > 0) ~ two_wheel_involved + truck_involved + unconcious_driver,
    data = (train_df),
    family = "binomial"
)

step3m.model <- glm(
    (`NUMBER OF PERSONS INJURED` > 0) ~ two_wheel_involved + truck_involved + crazy_driver,
    data = (train_df),
    family = "binomial"
)

# Foggy + Smoke + Heavy.Fog  + Ice.Fog + PRCP + SNOW + DayLight + at_crossing + two_wheel_involved + truck_involved + serious_area + unconcious_driver + crazy_driver

round3 <- round2 %>%
    mutate (
        aic_round3 = c(
        step3a.model$aic,
        step3b.model$aic,
        step3c.model$aic,
        step3d.model$aic,
        step3e.model$aic,
        step3f.model$aic,
        step3g.model$aic,
        step3h.model$aic,
        0,
        0,
        step3k.model$aic,
        step3l.model$aic,
        step3m.model$aic
    ))

round3 %>%
    arrange(aic_round3)

```

```{r }
# at_crossing

step4a.model <- glm(
    (`NUMBER OF PERSONS INJURED` > 0) ~ two_wheel_involved + truck_involved + at_crossing + Foggy,
    data = (train_df),
    family = "binomial"
)

step4b.model <- glm(
    (`NUMBER OF PERSONS INJURED` > 0) ~ two_wheel_involved + truck_involved + at_crossing + Smoke,
    data = (train_df),
    family = "binomial"
)

step4c.model <- glm(
    (`NUMBER OF PERSONS INJURED` > 0) ~ two_wheel_involved + truck_involved + at_crossing + Heavy.Fog,
    data = (train_df),
    family = "binomial"
)

step4d.model <- glm(
    (`NUMBER OF PERSONS INJURED` > 0) ~ two_wheel_involved + truck_involved + at_crossing + Ice.Fog,
    data = (train_df),
    family = "binomial"
)


step4e.model <- glm(
    (`NUMBER OF PERSONS INJURED` > 0) ~ two_wheel_involved + truck_involved + at_crossing + PRCP,
    data = (train_df),
    family = "binomial"
)

step4f.model <- glm(
    (`NUMBER OF PERSONS INJURED` > 0) ~ two_wheel_involved + truck_involved + at_crossing + SNOW,
    data = (train_df),
    family = "binomial"
)

step4g.model <- glm(
    (`NUMBER OF PERSONS INJURED` > 0) ~ two_wheel_involved + truck_involved + at_crossing + DayLight,
    data = (train_df),
    family = "binomial"
)

# h

# i

# j

step4k.model <- glm(
    (`NUMBER OF PERSONS INJURED` > 0) ~ two_wheel_involved + truck_involved + at_crossing + serious_area,
    data = (train_df),
    family = "binomial"
)

step4l.model <- glm(
    (`NUMBER OF PERSONS INJURED` > 0) ~ two_wheel_involved + truck_involved + at_crossing + unconcious_driver,
    data = (train_df),
    family = "binomial"
)

step4m.model <- glm(
    (`NUMBER OF PERSONS INJURED` > 0) ~ two_wheel_involved + truck_involved + at_crossing + crazy_driver,
    data = (train_df),
    family = "binomial"
)

# Foggy + Smoke + Heavy.Fog  + Ice.Fog + PRCP + SNOW + DayLight + at_crossing + two_wheel_involved + truck_involved + serious_area + unconcious_driver + crazy_driver

round4 <- round3 %>%
    mutate (
        aic_round4 = c(
        step4a.model$aic,
        step4b.model$aic,
        step4c.model$aic,
        step4d.model$aic,
        step4e.model$aic,
        step4f.model$aic,
        step4g.model$aic,
        0,
        0,
        0,
        step4k.model$aic,
        step4l.model$aic,
        step4m.model$aic
    ))

round4 %>%
    arrange(aic_round4)
```

```{r}
# crazy driver
step5a.model <- glm(
    (`NUMBER OF PERSONS INJURED` > 0) ~ two_wheel_involved + truck_involved + at_crossing + crazy_driver + Foggy,
    data = (train_df),
    family = "binomial"
)

step5b.model <- glm(
    (`NUMBER OF PERSONS INJURED` > 0) ~ two_wheel_involved + truck_involved + at_crossing + crazy_driver + Smoke,
    data = (train_df),
    family = "binomial"
)

step5c.model <- glm(
    (`NUMBER OF PERSONS INJURED` > 0) ~ two_wheel_involved + truck_involved + at_crossing + crazy_driver + Heavy.Fog,
    data = (train_df),
    family = "binomial"
)

step5d.model <- glm(
    (`NUMBER OF PERSONS INJURED` > 0) ~ two_wheel_involved + truck_involved + at_crossing + crazy_driver + Ice.Fog,
    data = (train_df),
    family = "binomial"
)


step5e.model <- glm(
    (`NUMBER OF PERSONS INJURED` > 0) ~ two_wheel_involved + truck_involved + at_crossing + crazy_driver + PRCP,
    data = (train_df),
    family = "binomial"
)

step5f.model <- glm(
    (`NUMBER OF PERSONS INJURED` > 0) ~ two_wheel_involved + truck_involved + at_crossing + crazy_driver + SNOW,
    data = (train_df),
    family = "binomial"
)

step5g.model <- glm(
    (`NUMBER OF PERSONS INJURED` > 0) ~ two_wheel_involved + truck_involved + at_crossing + crazy_driver + DayLight,
    data = (train_df),
    family = "binomial"
)

# h

# i

# j

step5k.model <- glm(
    (`NUMBER OF PERSONS INJURED` > 0) ~ two_wheel_involved + truck_involved + at_crossing + crazy_driver + serious_area,
    data = (train_df),
    family = "binomial"
)

step5l.model <- glm(
    (`NUMBER OF PERSONS INJURED` > 0) ~ two_wheel_involved + truck_involved + at_crossing + crazy_driver + unconcious_driver,
    data = (train_df),
    family = "binomial"
)

# m

# Foggy + Smoke + Heavy.Fog  + Ice.Fog + PRCP + SNOW + DayLight + at_crossing + two_wheel_involved + truck_involved + serious_area + unconcious_driver + crazy_driver

round5 <- round4 %>%
    mutate (
        aic_round5 = c(
        step5a.model$aic,
        step5b.model$aic,
        step5c.model$aic,
        step5d.model$aic,
        step5e.model$aic,
        step5f.model$aic,
        step5g.model$aic,
        0,
        0,
        0,
        step5k.model$aic,
        step5l.model$aic,
        0
    ))

round5 %>%
    arrange(aic_round5)
```

```{r}
# DayLight
step6a.model <- glm(
    (`NUMBER OF PERSONS INJURED` > 0) ~ two_wheel_involved + truck_involved + at_crossing + crazy_driver + DayLight + Foggy,
    data = (train_df),
    family = "binomial"
)

step6b.model <- glm(
    (`NUMBER OF PERSONS INJURED` > 0) ~ two_wheel_involved + truck_involved + at_crossing + crazy_driver + DayLight + Smoke,
    data = (train_df),
    family = "binomial"
)

step6c.model <- glm(
    (`NUMBER OF PERSONS INJURED` > 0) ~ two_wheel_involved + truck_involved + at_crossing + crazy_driver + DayLight + Heavy.Fog,
    data = (train_df),
    family = "binomial"
)

step6d.model <- glm(
    (`NUMBER OF PERSONS INJURED` > 0) ~ two_wheel_involved + truck_involved + at_crossing + crazy_driver + DayLight + Ice.Fog,
    data = (train_df),
    family = "binomial"
)


step6e.model <- glm(
    (`NUMBER OF PERSONS INJURED` > 0) ~ two_wheel_involved + truck_involved + at_crossing + crazy_driver + DayLight + PRCP,
    data = (train_df),
    family = "binomial"
)

step6f.model <- glm(
    (`NUMBER OF PERSONS INJURED` > 0) ~ two_wheel_involved + truck_involved + at_crossing + crazy_driver + DayLight + SNOW,
    data = (train_df),
    family = "binomial"
)

# g

# h

# i

# j

step6k.model <- glm(
    (`NUMBER OF PERSONS INJURED` > 0) ~ two_wheel_involved + truck_involved + at_crossing + crazy_driver + DayLight + serious_area,
    data = (train_df),
    family = "binomial"
)

step6l.model <- glm(
    (`NUMBER OF PERSONS INJURED` > 0) ~ two_wheel_involved + truck_involved + at_crossing + crazy_driver + DayLight + unconcious_driver,
    data = (train_df),
    family = "binomial"
)

# m

# Foggy + Smoke + Heavy.Fog  + Ice.Fog + PRCP + SNOW + DayLight + at_crossing + two_wheel_involved + truck_involved + serious_area + unconcious_driver + crazy_driver

round6 <- round5 %>%
    mutate (
        aic_round6 = c(
        step6a.model$aic,
        step6b.model$aic,
        step6c.model$aic,
        step6d.model$aic,
        step6e.model$aic,
        step6f.model$aic,
        0,
        0,
        0,
        0,
        step6k.model$aic,
        step6l.model$aic,
        0
    ))

round6 %>%
    arrange(aic_round6)

```


```{r}
# serious_area
step7a.model <- glm(
    (`NUMBER OF PERSONS INJURED` > 0) ~ two_wheel_involved + truck_involved + at_crossing + crazy_driver + DayLight + serious_area + Foggy,
    data = (train_df),
    family = "binomial"
)

step7b.model <- glm(
    (`NUMBER OF PERSONS INJURED` > 0) ~ two_wheel_involved + truck_involved + at_crossing + crazy_driver + DayLight + serious_area + Smoke,
    data = (train_df),
    family = "binomial"
)

step7c.model <- glm(
    (`NUMBER OF PERSONS INJURED` > 0) ~ two_wheel_involved + truck_involved + at_crossing + crazy_driver + DayLight + serious_area + Heavy.Fog,
    data = (train_df),
    family = "binomial"
)

step7d.model <- glm(
    (`NUMBER OF PERSONS INJURED` > 0) ~ two_wheel_involved + truck_involved + at_crossing + crazy_driver + DayLight + serious_area + Ice.Fog,
    data = (train_df),
    family = "binomial"
)


step7e.model <- glm(
    (`NUMBER OF PERSONS INJURED` > 0) ~ two_wheel_involved + truck_involved + at_crossing + crazy_driver + DayLight + serious_area + PRCP,
    data = (train_df),
    family = "binomial"
)

step7f.model <- glm(
    (`NUMBER OF PERSONS INJURED` > 0) ~ two_wheel_involved + truck_involved + at_crossing + crazy_driver + DayLight + serious_area + SNOW,
    data = (train_df),
    family = "binomial"
)

step7l.model <- glm(
    (`NUMBER OF PERSONS INJURED` > 0) ~ two_wheel_involved + truck_involved + at_crossing + crazy_driver + DayLight + serious_area + unconcious_driver,
    data = (train_df),
    family = "binomial"
)

# m

# Foggy + Smoke + Heavy.Fog  + Ice.Fog + PRCP + SNOW + DayLight + at_crossing + two_wheel_involved + truck_involved + serious_area + unconcious_driver + crazy_driver

round7 <- round6 %>%
    mutate (
        aic_round7 = c(
        step7a.model$aic,
        step7b.model$aic,
        step7c.model$aic,
        step7d.model$aic,
        step7e.model$aic,
        step7f.model$aic,
        0,
        0,
        0,
        0,
        0,
        step7l.model$aic,
        0
    ))

round7 %>%
    arrange(aic_round7)
```


```{r}
# SNOW 
step8a.model <- glm(
    (`NUMBER OF PERSONS INJURED` > 0) ~ two_wheel_involved + truck_involved + at_crossing + crazy_driver + DayLight + serious_area + SNOW + Foggy,
    data = (train_df),
    family = "binomial"
)

step8b.model <- glm(
    (`NUMBER OF PERSONS INJURED` > 0) ~ two_wheel_involved + truck_involved + at_crossing + crazy_driver + DayLight + serious_area + SNOW + Smoke,
    data = (train_df),
    family = "binomial"
)

step8c.model <- glm(
    (`NUMBER OF PERSONS INJURED` > 0) ~ two_wheel_involved + truck_involved + at_crossing + crazy_driver + DayLight + serious_area + SNOW + Heavy.Fog,
    data = (train_df),
    family = "binomial"
)

step8d.model <- glm(
    (`NUMBER OF PERSONS INJURED` > 0) ~ two_wheel_involved + truck_involved + at_crossing + crazy_driver + DayLight + serious_area + SNOW + Ice.Fog,
    data = (train_df),
    family = "binomial"
)


step8e.model <- glm(
    (`NUMBER OF PERSONS INJURED` > 0) ~ two_wheel_involved + truck_involved + at_crossing + crazy_driver + DayLight + serious_area + SNOW + PRCP,
    data = (train_df),
    family = "binomial"
)

step8l.model <- glm(
    (`NUMBER OF PERSONS INJURED` > 0) ~ two_wheel_involved + truck_involved + at_crossing + crazy_driver + DayLight + serious_area + SNOW + unconcious_driver,
    data = (train_df),
    family = "binomial"
)

# m

# Foggy + Smoke + Heavy.Fog  + Ice.Fog + PRCP + SNOW + DayLight + at_crossing + two_wheel_involved + truck_involved + serious_area + unconcious_driver + crazy_driver

round8 <- round7 %>%
    mutate (
        aic_round8 = c(
        step8a.model$aic,
        step8b.model$aic,
        step8c.model$aic,
        step8d.model$aic,
        step8e.model$aic,
        0,
        0,
        0,
        0,
        0,
        0,
        step8l.model$aic,
        0
    ))

round8 %>%
    arrange(aic_round8)
```


```{r}
# PRCP
step9a.model <- glm(
    (`NUMBER OF PERSONS INJURED` > 0) ~ two_wheel_involved + truck_involved + at_crossing + crazy_driver + DayLight + serious_area + SNOW + PRCP + Foggy,
    data = (train_df),
    family = "binomial"
)

step9b.model <- glm(
    (`NUMBER OF PERSONS INJURED` > 0) ~ two_wheel_involved + truck_involved + at_crossing + crazy_driver + DayLight + serious_area + SNOW + PRCP + Smoke,
    data = (train_df),
    family = "binomial"
)

step9c.model <- glm(
    (`NUMBER OF PERSONS INJURED` > 0) ~ two_wheel_involved + truck_involved + at_crossing + crazy_driver + DayLight + serious_area + SNOW + PRCP + Heavy.Fog,
    data = (train_df),
    family = "binomial"
)

step9d.model <- glm(
    (`NUMBER OF PERSONS INJURED` > 0) ~ two_wheel_involved + truck_involved + at_crossing + crazy_driver + DayLight + serious_area + SNOW + PRCP + Ice.Fog,
    data = (train_df),
    family = "binomial"
)

step9l.model <- glm(
    (`NUMBER OF PERSONS INJURED` > 0) ~ two_wheel_involved + truck_involved + at_crossing + crazy_driver + DayLight + serious_area + SNOW + PRCP + unconcious_driver,
    data = (train_df),
    family = "binomial"
)

# Foggy + Smoke + Heavy.Fog  + Ice.Fog + PRCP + SNOW + DayLight + at_crossing + two_wheel_involved + truck_involved + serious_area + unconcious_driver + crazy_driver

round9 <- round8 %>%
    mutate (
        aic_round9 = c(
        step9a.model$aic,
        step9b.model$aic,
        step9c.model$aic,
        step9d.model$aic,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        step9l.model$aic,
        0
    ))

round9 %>%
    arrange(aic_round9)

```
```{r}
# Smoke
step10a.model <- glm(
    (`NUMBER OF PERSONS INJURED` > 0) ~ two_wheel_involved + truck_involved + at_crossing + crazy_driver + DayLight + serious_area + SNOW + PRCP + Smoke + Foggy,
    data = (train_df),
    family = "binomial"
)

step10c.model <- glm(
    (`NUMBER OF PERSONS INJURED` > 0) ~ two_wheel_involved + truck_involved + at_crossing + crazy_driver + DayLight + serious_area + SNOW + PRCP + Smoke + Heavy.Fog,
    data = (train_df),
    family = "binomial"
)

step10d.model <- glm(
    (`NUMBER OF PERSONS INJURED` > 0) ~ two_wheel_involved + truck_involved + at_crossing + crazy_driver + DayLight + serious_area + SNOW + PRCP + Smoke + Ice.Fog,
    data = (train_df),
    family = "binomial"
)

step10l.model <- glm(
    (`NUMBER OF PERSONS INJURED` > 0) ~ two_wheel_involved + truck_involved + at_crossing + crazy_driver + DayLight + serious_area + SNOW + PRCP + Smoke + unconcious_driver,
    data = (train_df),
    family = "binomial"
)

# Foggy + Smoke + Heavy.Fog  + Ice.Fog + PRCP + SNOW + DayLight + at_crossing + two_wheel_involved + truck_involved + serious_area + unconcious_driver + crazy_driver

round10 <- round9 %>%
    mutate (
        aic_round10 = c(
        step10a.model$aic,
        0,
        step10c.model$aic,
        step10d.model$aic,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        step10l.model$aic,
        0
    ))

round10 %>%
    arrange(aic_round10)

```
```{r}
# Foggy
step11c.model <- glm(
    (`NUMBER OF PERSONS INJURED` > 0) ~ two_wheel_involved + truck_involved + at_crossing + crazy_driver + DayLight + serious_area + SNOW + PRCP + Smoke + Foggy + Heavy.Fog,
    data = (train_df),
    family = "binomial"
)

step11d.model <- glm(
    (`NUMBER OF PERSONS INJURED` > 0) ~ two_wheel_involved + truck_involved + at_crossing + crazy_driver + DayLight + serious_area + SNOW + PRCP + Smoke + Foggy + Ice.Fog,
    data = (train_df),
    family = "binomial"
)

step11l.model <- glm(
    (`NUMBER OF PERSONS INJURED` > 0) ~ two_wheel_involved + truck_involved + at_crossing + crazy_driver + DayLight + serious_area + SNOW + PRCP + Smoke + Foggy + unconcious_driver,
    data = (train_df),
    family = "binomial"
)

# Foggy + Smoke + Heavy.Fog  + Ice.Fog + PRCP + SNOW + DayLight + at_crossing + two_wheel_involved + truck_involved + serious_area + unconcious_driver + crazy_driver

round11 <- round10 %>%
    mutate (
        aic_round11 = c(
        0,
        0,
        step11c.model$aic,
        step11d.model$aic,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        step11l.model$aic,
        0
    ))

round11 %>%
    arrange(aic_round11)

```


```{r}
# Ice.Fog
step12c.model <- glm(
    (`NUMBER OF PERSONS INJURED` > 0) ~ two_wheel_involved + truck_involved + at_crossing + crazy_driver + DayLight + serious_area + SNOW + PRCP + Smoke + Foggy + Ice.Fog + Heavy.Fog,
    data = (train_df),
    family = "binomial"
)

step12l.model <- glm(
    (`NUMBER OF PERSONS INJURED` > 0) ~ two_wheel_involved + truck_involved + at_crossing + crazy_driver + DayLight + serious_area + SNOW + PRCP + Smoke + Foggy + Ice.Fog + unconcious_driver,
    data = (train_df),
    family = "binomial"
)

# Foggy + Smoke + Heavy.Fog  + Ice.Fog + PRCP + SNOW + DayLight + at_crossing + two_wheel_involved + truck_involved + serious_area + unconcious_driver + crazy_driver

round12 <- round11 %>%
    mutate (
        aic_round12 = c(
        0,
        0,
        step12c.model$aic,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        step12l.model$aic,
        0
    ))

round12 %>%
    arrange(aic_round12)

```

```{r}
# unconcious_driver
step13c.model <- glm(
    (`NUMBER OF PERSONS INJURED` > 0) ~ two_wheel_involved + truck_involved + at_crossing + crazy_driver + DayLight + serious_area + SNOW + PRCP + Smoke + Foggy + Ice.Fog + unconcious_driver + Heavy.Fog,
    data = (train_df),
    family = "binomial"
)

# Foggy + Smoke + Heavy.Fog  + Ice.Fog + PRCP + SNOW + DayLight + at_crossing + two_wheel_involved + truck_involved + serious_area + unconcious_driver + crazy_driver

round13 <- round12 %>%
    mutate (
        aic_round13 = c(
        0,
        0,
        step13c.model$aic,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
    ))

round13 %>%
    arrange(aic_round13)

```
```{r}
# Foggy + Smoke + Heavy.Fog  + Ice.Fog + PRCP + SNOW + DayLight + at_crossing + two_wheel_involved + truck_involved + serious_area + unconcious_driver + crazy_driver

model_selection <- round13 %>%
    mutate (
        aic_round14 = c(
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
    ))

model_selection %>%
    head(11)
```

```{r randomForest}
library(randomForest)

af2 <- accidents_full %>%
    select(Foggy, Smoke, Heavy.Fog, `VEHICLE TYPE CODE 1`, TMAX, TMIN, `CONTRIBUTING FACTOR VEHICLE 1`, PRCP, SNOW, Ice.Fog, DayLight, vehicle, `BOROUGH`, `LOCATION_SPLIT`, `CROSS STREET`, `NUMBER OF PERSONS INJURED`, `LATITUDE`, `LONGITUDE`) %>%
    drop_na()

sampleIndex <- sample(nrow(af), 25000)

af2 <- af2 %>%
    rename(
        `vehicle_type_code_1` = `VEHICLE TYPE CODE 1`,
        `contributing_factor_vehicle_1` = `CONTRIBUTING FACTOR VEHICLE 1`,
        `cross` = `CROSS STREET`
    )

r1 <- randomForest(
    as.factor(`NUMBER OF PERSONS INJURED` > 0) ~ LATITUDE + LONGITUDE,
    mtry = 1,
    data = af2,
    subset = sampleIndex,
    ntree = 1000
)


sample2Index <- sample(nrow(af2), 50000)

injury_position2 <- predict(r1, newdata = af2[sample2Index, ], type = "response")

tibble(
    mark = injury_position2,
    LONGITUDE = af2[sample2Index, ]$LONGITUDE,
    LATITUDE = af2[sample2Index, ]$LATITUDE
) %>%
    ggplot(aes(x = `LATITUDE`, y = `LONGITUDE`, color = mark)) +
    geom_point(aes(
        alpha =
            ifelse(mark == "TRUE", 0.5, 0.1)
    ))
```

```{r}

trainingAndTestingSet <- trainingAndTesting(accidents_full, ratio = 0.7)
trainingAndTestingSet

lm1 <- lm(
    `NUMBER OF PERSONS INJURED` ~ Foggy * Heavy.Fog + Smoke +
        `VEHICLE TYPE CODE 1` + TMAX + TMIN +
        `CONTRIBUTING FACTOR VEHICLE 1` + PRCP + SNOW + Ice.Fog + DayLight,
    data = (trainingAndTestingSet[[1]])
)

lm2 <- glm(
    (`NUMBER OF PERSONS INJURED` > 0) ~ Foggy + Smoke +
        `VEHICLE TYPE CODE 1` + `CONTRIBUTING FACTOR VEHICLE 1` +
        PRCP + SNOW + DayLight + `BOROUGH`,
    data = trainingAndTestingSet[[1]],
    family = "binomial"
)

lm3 <- glm(
    `NUMBER OF PERSONS INJURED` ~ Foggy + Smoke +
        `VEHICLE TYPE CODE 1` + `CONTRIBUTING FACTOR VEHICLE 1` +
        PRCP + SNOW + DayLight + `BOROUGH` + `LOCATION_SPLIT`,
    data = (
        ((trainingAndTestingSet[[1]] %>%
            drop_na(
                Foggy, Heavy.Fog, Smoke,
                `VEHICLE TYPE CODE 1`,
                `CONTRIBUTING FACTOR VEHICLE 1`,
                PRCP, SNOW, DayLight
            )))),
    family = "poisson"
)

summary(lm1)

summary(lm2)

summary(lm3)
```

```{r}
mean(
    (trainingAndTestingSet[[2]]$`NUMBER OF PERSONS INJURED` > 0) == (predict(lm2,
        newdata = trainingAndTestingSet[[2]],
        type = "response"
    ) > 0.5),
    na.rm = T
)

test.predict <- (tibble(injury = (predict(lm3,
    newdata = trainingAndTestingSet[[2]], type = "response"
) > 0.5)) %>% drop_na())$injury

test.actual <- (
    ((trainingAndTestingSet[[2]] %>%
        drop_na(
            Foggy, Heavy.Fog, Smoke,
            `VEHICLE TYPE CODE 1`,
            `CONTRIBUTING FACTOR VEHICLE 1`,
            PRCP, SNOW, DayLight
        ))
    ["NUMBER OF PERSONS INJURED"]) > 0)


quantile(predict(lm2, type = "response"), na.rm = FALSE, names = TRUE)
quantile(accidents_full$`NUMBER OF PERSONS INJURED`, na.rm = T)


tibble(
    Type = c("Injury", "No Injury"),
    Prediction = c(
        (sum(test.predict, na.rm = T)),
        (sum(!test.predict, na.rm = T))
    ),
    Actual = c(
        sum(
            test.actual,
            na.rm = T
        ),
        sum(
            !test.actual,
            na.rm = T
        )
    ),
    Accuracy = c(
        sum(
            (test.actual & test.predict),
            na.rm = T
        ) / sum(test.actual),
        sum(
            (!test.actual & !test.predict),
            na.rm = T
        ) / sum(!test.actual)
    )
)
```





